<span style="margin:2% 0% 3% 0%; float:left; width:100%; margin-top:20%;">
Report Generated By <a href="https://<?= @$website; ?>" target="_blank" style="color:#006699; text-decoration:none;"><?= @$abbreviation; ?> Reporting System</a><br> 
On <?= date('l d-m-Y h:i:s A'); ?> <br>
Printed by <b><?= $_SESSION['position_name'].', '.$_SESSION['user_othername'].' '.$_SESSION['user_name']; ?></b></span>